### ISSUE TITLE
Sonarr Auth+ Reverse Proxy Breaks Bot

### ISSUE THREAD

**Issue by fiservedpi** [CyaOnDaNet/plex_discord_role_management#15]
I’ve set up Sonarr Forms Authentication, as well as reverse proxy. With this enabled the bot cannot connect via api key. Sonarr keeps blocking the bot. I’d like to keep browser Auth on and still have the bot be able to access Sonarr via API Key 
![7EAF475C-56E5-49A6-95D0-F74D0E1F5784](https://user-images.githubusercontent.com/42981853/138575151-48494008-d2ac-4321-aa47-044a816fc9c5.jpeg)

**Comment by fiservedpi** [comment]
`2021-10-23 18:55:07.7|Info|Auth|Auth-Unauthorized ip xxx.xxx.x.xx url 'http://mydomain.sonarr.com`

From Bot
‘FetchError: request to 
http://192.168.1.10:8989/api/api key-xxxxxxx failed, reason: connect EHOSTUNREACH 192.168.1.10:8989`

`at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
at ClientRequest.emit (events.js:314:20)
at Socket.socketErrorListener (_http_client.js:428:9)
at Socket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
type: 'system',
errno: 'EHOSTUNREACH',
code: 'EHOSTUNREACH'
}`
`Couldn't connect to Sonarr, check your settings. 
TypeError [INVALID_TYPE]: Supplied roles is not a Role, Snowflake or Array or Collection of Roles or Snowflakes.
at GuildMemberRoleManager.add (/app/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:93:15)
at Job.job (/app/index.js:396:34)
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[Symbol(code)]: 'INVALID_TYPE'
}`

**Comment by fiservedpi** [comment]
May not be that simple although this issue was closed as fixed but I cannot see the correct way to use api keys through a reverse proxy 
https://github.com/Sonarr/Sonarr/issues/3711

The mind boggling thing is I can hit the url directly and it works

`http://192.168.1.10:8989/api/series?apikey=redacted


![24440474-C585-416D-A1BF-4136F108F4E8](https://user-images.githubusercontent.com/42981853/138575584-2bc56ae0-d852-472c-b3d3-d9b6cfe4acc3.jpeg)
 `
