### ISSUE TITLE
Error: Cannot find module 'discord.js'

### ISSUE THREAD

**Issue by mckenna654** [CyaOnDaNet/plex_discord_role_management#30]
Hi,

Followed the installation guide on my Debian machine however getting the following error when running node index.json.

```
(plex) mckenna654@reddiscordbot-1:~/plex_discord_role_management$ node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/mckenna654/plex_discord_role_management/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/mckenna654/plex_discord_role_management/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/mckenna654/plex_discord_role_management/index.js' ]
```

**Comment by RappyTV** [comment]
you have to execute `npm install` or `npm i` to install all the required packages
